site_name: Engineering Portfolio & Handbook - Harry Chen
theme:
    name: mkdocs
    custom_dir: theme/
markdown_extensions:
  - md_in_html
nav:
  - About Me: 'about-me.md'
  - Products: 'design-products.md'
  - Processes: 'design-processes.md'
  - TMFs: 'tmf.md'
  - Appendix: 'appendix.md'